import type { Product } from '@/types/product'

// Brands used across the catalog
// Tiny Trails, Cub Club, Happy Feet Kids, PlayWorks, Little Learners,
// Sunny Sprouts, Giggle Gear, Nest & Nook, Bright Buddy, Wobble Walk

export const products: Product[] = [
  // ===================== CLOTHING (20+) =====================
  {
    id: 'p1',
    sku: 'LN-CL-0001',
    slug: 'girls-floral-cotton-dress',
    name: 'Girls Floral Cotton Dress',
    brand: 'Tiny Trails',
    category: 'clothing',
    subcategory: 'Dresses',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A breezy floral print dress made from 100% breathable cotton, perfect for daily wear and summer outings. Features a comfortable elastic waist and soft finish that keeps little ones cool all day. Machine washable and colorfast for long-lasting wear.',
    shortDescription: 'Breezy floral cotton dress for everyday summer wear.',
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80'],
    price: 799,
    mrp: 1199,
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y'],
    colors: [
      { name: 'Coral Pink', hex: '#e8927c' },
      { name: 'Lemon Yellow', hex: '#f4d35e' },
    ],
    material: '100% Cotton',
    careInstructions: 'Machine wash cold, tumble dry low',
    rating: 4.5,
    reviewCount: 132,
    onlineStock: 24,
    storeStock: 10,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['cotton', 'summer', 'floral', 'casual'],
  },
  {
    id: 'p2',
    sku: 'LN-CL-0002',
    slug: 'boys-printed-casual-tshirt',
    name: 'Boys Printed Casual T-Shirt',
    brand: 'Cub Club',
    category: 'clothing',
    subcategory: 'T-Shirts',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A fun graphic tee crafted from soft cotton jersey fabric that is gentle on sensitive skin. The relaxed fit allows freedom of movement for active play. Pairs easily with shorts or jeans for a casual everyday look.',
    shortDescription: 'Soft cotton graphic tee for everyday play.',
    images: ['https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80'],
    price: 349,
    mrp: 499,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y'],
    colors: [
      { name: 'Sky Blue', hex: '#8ec9e8' },
      { name: 'Charcoal Grey', hex: '#4a4a4a' },
    ],
    material: '100% Cotton',
    careInstructions: 'Machine wash cold, do not bleach',
    rating: 4.2,
    reviewCount: 87,
    onlineStock: 40,
    storeStock: 15,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['cotton', 'casual', 'graphic-print'],
  },
  {
    id: 'p3',
    sku: 'LN-CL-0003',
    slug: 'kids-denim-jacket',
    name: 'Kids Denim Jacket',
    brand: 'Tiny Trails',
    category: 'clothing',
    subcategory: 'Jackets',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A classic denim jacket with sturdy button closures and functional front pockets. Layers perfectly over t-shirts and dresses for cooler evenings. Durable stitching ensures it withstands rough and tumble play.',
    shortDescription: 'Classic durable denim jacket for layering.',
    images: ['https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80'],
    price: 1299,
    mrp: 1899,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y'],
    colors: [{ name: 'Classic Blue', hex: '#3b5998' }],
    material: 'Denim, 98% Cotton 2% Elastane',
    careInstructions: 'Machine wash cold, inside out',
    rating: 4.6,
    reviewCount: 54,
    onlineStock: 12,
    storeStock: 8,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: false,
    trending: true,
    tags: ['denim', 'jacket', 'winter', 'layering'],
  },
  {
    id: 'p4',
    sku: 'LN-CL-0004',
    slug: 'New Born-cotton-romper',
    name: 'New Born Cotton Romper',
    brand: 'Nest & Nook',
    category: 'clothing',
    subcategory: 'Rompers',
    gender: 'New Born',
    ageGroup: ['0-3m', '3-12m'],
    description:
      'An ultra-soft romper designed for delicate New Born skin, with poppers at the bottom for easy diaper changes. The lightweight cotton fabric keeps New Born comfortable through naps and playtime alike. A wardrobe essential for new parents.',
    shortDescription: 'Ultra-soft everyday romper for babies.',
    images: ['https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80'],
    price: 449,
    mrp: 599,
    sizes: ['0-3M', '3-6M', '6-9M'],
    colors: [
      { name: 'Mint Green', hex: '#a8e6cf' },
      { name: 'Soft Peach', hex: '#f7d9c4' },
      { name: 'White', hex: '#ffffff' },
    ],
    material: '100% Cotton',
    careInstructions: 'Hand wash recommended, mild detergent',
    rating: 4.7,
    reviewCount: 210,
    onlineStock: 30,
    storeStock: 20,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['cotton', 'New Born', 'romper', 'newborn'],
  },
  {
    id: 'p5',
    sku: 'LN-CL-0005',
    slug: 'girls-party-frock',
    name: 'Girls Party Frock',
    brand: 'Sunny Sprouts',
    category: 'clothing',
    subcategory: 'Party Wear',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'An elegant net and satin frock with delicate embroidery, ideal for birthdays and festive celebrations. The layered tulle skirt adds a princess-like flair that little girls love. Comes with a soft inner lining for all-day comfort.',
    shortDescription: 'Elegant embroidered frock for special occasions.',
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80'],
    price: 1599,
    mrp: 2499,
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y'],
    colors: [
      { name: 'Wine Red', hex: '#8b1e3f' },
      { name: 'Royal Blue', hex: '#2b3a67' },
    ],
    material: 'Net and Satin',
    careInstructions: 'Dry clean only',
    rating: 4.8,
    reviewCount: 66,
    onlineStock: 9,
    storeStock: 6,
    pickupAvailable: true,
    featured: true,
    newArrival: true,
    bestSeller: false,
    trending: true,
    tags: ['party', 'festive', 'embroidered', 'frock'],
  },
  {
    id: 'p6',
    sku: 'LN-CL-0006',
    slug: 'boys-ethnic-kurta-set',
    name: 'Boys Ethnic Kurta Set',
    brand: 'Cub Club',
    category: 'clothing',
    subcategory: 'Ethnic Wear',
    gender: 'boys',
    ageGroup: ['1-3y', '4-7y', '8-12y'],
    description:
      'A traditional kurta-pyjama set in rich festive fabric, perfect for weddings and Diwali celebrations. Features intricate thread work on the collar and a comfortable drawstring pyjama. Lightweight fabric ensures ease of movement during festivities.',
    shortDescription: 'Traditional kurta-pyjama set for festive occasions.',
    images: ['https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80'],
    price: 1099,
    mrp: 1599,
    sizes: ['2-3Y', '4-5Y', '6-7Y', '8-9Y', '10-11Y'],
    colors: [
      { name: 'Mustard Yellow', hex: '#d4a017' },
      { name: 'Maroon', hex: '#6d1b2f' },
    ],
    material: 'Silk Blend',
    careInstructions: 'Dry clean only',
    rating: 4.4,
    reviewCount: 41,
    onlineStock: 15,
    storeStock: 5,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['ethnic', 'festive', 'kurta', 'wedding'],
  },
  {
    id: 'p7',
    sku: 'LN-CL-0007',
    slug: 'girls-denim-leggings',
    name: 'Girls Denim Leggings',
    brand: 'Giggle Gear',
    category: 'clothing',
    subcategory: 'Leggings',
    gender: 'girls',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'Stretchable jeggings that combine the look of denim with the comfort of leggings. An elastic waistband and four-way stretch fabric make these ideal for school and play. Fades resistant with reinforced stitching.',
    shortDescription: 'Stretchable denim-look jeggings for everyday comfort.',
    images: ['https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    price: 599,
    mrp: 799,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y'],
    colors: [{ name: 'Indigo Blue', hex: '#37456a' }],
    material: '78% Cotton 20% Polyester 2% Elastane',
    careInstructions: 'Machine wash cold, inside out',
    rating: 4.3,
    reviewCount: 58,
    onlineStock: 27,
    storeStock: 12,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['denim', 'leggings', 'school', 'stretch'],
  },
  {
    id: 'p8',
    sku: 'LN-CL-0008',
    slug: 'boys-checked-shirt',
    name: 'Boys Checked Casual Shirt',
    brand: 'Cub Club',
    category: 'clothing',
    subcategory: 'T-Shirts',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y', '13-16y'],
    description:
      'A crisp checkered shirt made from breathable cotton poplin, great for school events and casual outings alike. Button-down front and curved hem give it a smart-casual finish. Easy to pair with chinos or denims.',
    shortDescription: 'Crisp cotton checkered shirt for smart-casual looks.',
    images: ['https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80'],
    price: 649,
    mrp: 899,
    sizes: ['6-7Y', '7-8Y', '8-9Y', '10-11Y', '12-13Y'],
    colors: [
      { name: 'Red Check', hex: '#b33951' },
      { name: 'Green Check', hex: '#3f704d' },
    ],
    material: '100% Cotton Poplin',
    careInstructions: 'Machine wash cold, iron on low',
    rating: 4.1,
    reviewCount: 33,
    onlineStock: 18,
    storeStock: 7,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['checked', 'shirt', 'smart-casual'],
  },
  {
    id: 'p9',
    sku: 'LN-CL-0009',
    slug: 'girls-cotton-nightsuit',
    name: 'Girls Cotton Nightsuit',
    brand: 'Nest & Nook',
    category: 'clothing',
    subcategory: 'Nightwear',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A cozy two-piece nightsuit in soft cotton hosiery fabric, printed with cute unicorn motifs. The relaxed fit ensures comfortable sleep through the night. Skin-friendly and breathable for year-round use.',
    shortDescription: 'Cozy printed cotton nightsuit for comfortable sleep.',
    images: ['https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&w=800&q=80'],
    price: 499,
    mrp: 699,
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y'],
    colors: [{ name: 'Lavender', hex: '#c9b6e4' }],
    material: '100% Cotton Hosiery',
    careInstructions: 'Machine wash cold',
    rating: 4.5,
    reviewCount: 74,
    onlineStock: 22,
    storeStock: 9,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['nightwear', 'cotton', 'sleepwear'],
  },
  {
    id: 'p10',
    sku: 'LN-CL-0010',
    slug: 'kids-hooded-sweatshirt',
    name: 'Kids Hooded Sweatshirt',
    brand: 'PlayWorks',
    category: 'clothing',
    subcategory: 'Jackets',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A warm fleece-lined hoodie designed to keep kids cozy during winter mornings and evening play. Features a kangaroo pocket and adjustable drawstring hood. Soft brushed interior adds extra warmth without bulk.',
    shortDescription: 'Warm fleece-lined hoodie for winter days.',
    images: ['https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80'],
    price: 899,
    mrp: 1299,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y'],
    colors: [
      { name: 'Charcoal Grey', hex: '#4a4a4a' },
      { name: 'Navy Blue', hex: '#1f2a44' },
    ],
    material: '80% Cotton 20% Polyester Fleece',
    careInstructions: 'Machine wash cold, do not tumble dry',
    rating: 4.4,
    reviewCount: 49,
    onlineStock: 20,
    storeStock: 11,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: true,
    tags: ['winter', 'hoodie', 'fleece', 'warm'],
  },
  {
    id: 'p11',
    sku: 'LN-CL-0011',
    slug: 'New Born-bodysuit-pack',
    name: 'New Born Bodysuit Pack of 3',
    brand: 'Nest & Nook',
    category: 'clothing',
    subcategory: 'Bodysuits',
    gender: 'New Born',
    ageGroup: ['0-3m', '3-12m'],
    description:
      'A pack of three snug-fit bodysuits in soft interlock cotton fabric, ideal for daily wear and layering. Envelope neckline makes dressing hassle-free for parents. Reinforced popper closures for durability through frequent washes.',
    shortDescription: 'Pack of 3 soft cotton bodysuits for babies.',
    images: ['https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80'],
    price: 649,
    mrp: 899,
    sizes: ['0-3M', '3-6M', '6-9M', '9-12M'],
    colors: [
      { name: 'White', hex: '#ffffff' },
      { name: 'Powder Blue', hex: '#cfe3f7' },
    ],
    material: '100% Cotton Interlock',
    careInstructions: 'Machine wash warm, mild detergent',
    rating: 4.6,
    reviewCount: 158,
    onlineStock: 35,
    storeStock: 18,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['New Born', 'bodysuit', 'cotton', 'essentials'],
  },
  {
    id: 'p12',
    sku: 'LN-CL-0012',
    slug: 'girls-denim-shorts',
    name: 'Girls Denim Shorts',
    brand: 'Giggle Gear',
    category: 'clothing',
    subcategory: 'Shorts',
    gender: 'girls',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'Comfortable denim shorts with a soft elasticated waistband and decorative front pockets. Perfect for summer outings and casual play. Durable fabric that holds its shape through countless washes.',
    shortDescription: 'Comfortable elasticated denim shorts for summer.',
    images: ['https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1444840535719-195841cb6e2b?auto=format&fit=crop&w=800&q=80'],
    price: 549,
    mrp: 749,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y'],
    colors: [{ name: 'Light Wash Blue', hex: '#a9c4dc' }],
    material: '98% Cotton 2% Elastane',
    careInstructions: 'Machine wash cold',
    rating: 4.0,
    reviewCount: 27,
    onlineStock: 16,
    storeStock: 4,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['denim', 'shorts', 'summer'],
  },
  {
    id: 'p13',
    sku: 'LN-CL-0013',
    slug: 'boys-track-suit-set',
    name: 'Boys Track Suit Set',
    brand: 'PlayWorks',
    category: 'clothing',
    subcategory: 'T-Shirts',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A sporty two-piece tracksuit made from moisture-wicking fabric, ideal for sports day and active play. Ribbed cuffs and elastic waistband ensure a secure, comfortable fit during movement. Lightweight and quick-drying.',
    shortDescription: 'Sporty moisture-wicking tracksuit for active kids.',
    images: ['https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80'],
    price: 949,
    mrp: 1399,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y'],
    colors: [
      { name: 'Black', hex: '#1a1a1a' },
      { name: 'Royal Blue', hex: '#2b3a67' },
    ],
    material: 'Polyester Dri-fit',
    careInstructions: 'Machine wash cold, do not iron print',
    rating: 4.3,
    reviewCount: 39,
    onlineStock: 14,
    storeStock: 6,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['sports', 'tracksuit', 'activewear'],
  },
  {
    id: 'p14',
    sku: 'LN-CL-0014',
    slug: 'girls-ruffle-top',
    name: 'Girls Ruffle Sleeve Top',
    brand: 'Sunny Sprouts',
    category: 'clothing',
    subcategory: 'T-Shirts',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A charming top with ruffled sleeves and a playful bow detail at the neckline, made from soft rayon blend fabric. Easy to pair with skirts, jeans, or leggings. A versatile addition to any little girl wardrobe.',
    shortDescription: 'Playful ruffle-sleeve top with bow detail.',
    images: ['https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80'],
    price: 449,
    mrp: 599,
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y'],
    colors: [
      { name: 'Blush Pink', hex: '#f2c6c2' },
      { name: 'White', hex: '#ffffff' },
    ],
    material: 'Rayon Blend',
    careInstructions: 'Hand wash cold',
    rating: 4.2,
    reviewCount: 21,
    onlineStock: 19,
    storeStock: 8,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['top', 'ruffle', 'casual'],
  },
  {
    id: 'p15',
    sku: 'LN-CL-0015',
    slug: 'kids-raincoat-with-bag',
    name: 'Kids Raincoat with Bag',
    brand: 'Tiny Trails',
    category: 'clothing',
    subcategory: 'Jackets',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A waterproof raincoat with a matching storage pouch, designed to keep kids dry during monsoon commutes. Reflective strips improve visibility in low light. Breathable lining prevents overheating while worn.',
    shortDescription: 'Waterproof raincoat with reflective strips and pouch.',
    images: ['https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80'],
    price: 699,
    mrp: 999,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y'],
    colors: [
      { name: 'Bright Yellow', hex: '#f4d35e' },
      { name: 'Red', hex: '#c1272d' },
    ],
    material: 'PVC Coated Polyester',
    careInstructions: 'Wipe clean with damp cloth',
    rating: 4.4,
    reviewCount: 45,
    onlineStock: 0,
    storeStock: 13,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['monsoon', 'raincoat', 'waterproof'],
  },
  {
    id: 'p16',
    sku: 'LN-CL-0016',
    slug: 'girls-woolen-cardigan',
    name: 'Girls Woolen Cardigan',
    brand: 'Nest & Nook',
    category: 'clothing',
    subcategory: 'Jackets',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A cable-knit cardigan crafted from soft acrylic wool blend, ideal for layering over dresses in winter. Button-front closure and ribbed cuffs add a classic touch. Warm yet lightweight for all-day comfort.',
    shortDescription: 'Cable-knit cardigan for warm winter layering.',
    images: ['https://images.unsplash.com/photo-1487956382158-bb926046304a?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80'],
    price: 899,
    mrp: 1299,
    sizes: ['2-3Y', '3-4Y', '4-5Y', '5-6Y'],
    colors: [{ name: 'Cream', hex: '#f4ecd8' }],
    material: 'Acrylic Wool Blend',
    careInstructions: 'Hand wash cold, dry flat',
    rating: 4.5,
    reviewCount: 30,
    onlineStock: 11,
    storeStock: 5,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['winter', 'cardigan', 'wool'],
  },
  {
    id: 'p17',
    sku: 'LN-CL-0017',
    slug: 'boys-formal-shirt-set',
    name: 'Boys Formal Shirt and Trouser Set',
    brand: 'Cub Club',
    category: 'clothing',
    subcategory: 'Party Wear',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A smart formal set with a crisp collared shirt and matching trousers, perfect for weddings and family functions. Wrinkle-resistant fabric keeps the outfit sharp all day. Includes a coordinated bow-tie accent.',
    shortDescription: 'Smart formal shirt and trouser set for occasions.',
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80'],
    price: 1399,
    mrp: 1999,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y', '8-9Y'],
    colors: [{ name: 'White', hex: '#ffffff' }, { name: 'Sky Blue', hex: '#8ec9e8' }],
    material: 'Cotton Blend',
    careInstructions: 'Dry clean recommended',
    rating: 4.6,
    reviewCount: 22,
    onlineStock: 8,
    storeStock: 4,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['formal', 'party', 'wedding'],
  },
  {
    id: 'p18',
    sku: 'LN-CL-0018',
    slug: 'girls-summer-jumpsuit',
    name: 'Girls Summer Jumpsuit',
    brand: 'Sunny Sprouts',
    category: 'clothing',
    subcategory: 'Dresses',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A playful jumpsuit in lightweight cotton poplin with adjustable shoulder straps and a frill hem. Great for beach trips and casual summer days. Snap closures make diaper changes and dressing quick and easy.',
    shortDescription: 'Playful cotton jumpsuit for summer outings.',
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80'],
    price: 649,
    mrp: 899,
    sizes: ['2-3Y', '3-4Y', '4-5Y'],
    colors: [{ name: 'Turquoise', hex: '#3fb8af' }],
    material: '100% Cotton Poplin',
    careInstructions: 'Machine wash cold',
    rating: 4.1,
    reviewCount: 18,
    onlineStock: 13,
    storeStock: 0,
    pickupAvailable: false,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['summer', 'jumpsuit', 'beachwear'],
  },
  {
    id: 'p19',
    sku: 'LN-CL-0019',
    slug: 'kids-thermal-innerwear-set',
    name: 'Kids Thermal Innerwear Set',
    brand: 'Nest & Nook',
    category: 'clothing',
    subcategory: 'Nightwear',
    gender: 'unisex',
    ageGroup: ['3-12m', '1-3y', '4-7y'],
    description:
      'A warm thermal top and pyjama set designed to be worn under regular clothing during peak winter. Brushed inner fleece traps heat while remaining breathable. Tagless design avoids irritation on sensitive skin.',
    shortDescription: 'Warm thermal innerwear set for peak winter.',
    images: ['https://images.unsplash.com/photo-1544776193-352d25ca82cd?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1544126592-807ade215a0b?auto=format&fit=crop&w=800&q=80'],
    price: 549,
    mrp: 749,
    sizes: ['1-2Y', '2-3Y', '3-4Y', '4-5Y'],
    colors: [{ name: 'Grey Melange', hex: '#a9a9a9' }],
    material: 'Cotton Fleece Blend',
    careInstructions: 'Machine wash warm',
    rating: 4.3,
    reviewCount: 26,
    onlineStock: 21,
    storeStock: 9,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['thermal', 'winter', 'innerwear'],
  },
  {
    id: 'p20',
    sku: 'LN-CL-0020',
    slug: 'girls-pleated-skirt',
    name: 'Girls Pleated Skirt',
    brand: 'Giggle Gear',
    category: 'clothing',
    subcategory: 'Dresses',
    gender: 'girls',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A twirl-worthy pleated skirt in soft crepe fabric with an elasticated waist for all-day comfort. Perfect for school events, parties, or casual outfits paired with a tee. Retains its pleat shape wash after wash.',
    shortDescription: 'Twirl-worthy pleated skirt for parties and play.',
    images: ['https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80'],
    price: 549,
    mrp: 799,
    sizes: ['4-5Y', '5-6Y', '6-7Y', '7-8Y'],
    colors: [{ name: 'Blush Pink', hex: '#f2c6c2' }, { name: 'Black', hex: '#1a1a1a' }],
    material: 'Crepe',
    careInstructions: 'Hand wash cold',
    rating: 4.0,
    reviewCount: 15,
    onlineStock: 17,
    storeStock: 6,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['skirt', 'pleated', 'party'],
  },
  {
    id: 'p21',
    sku: 'LN-CL-0021',
    slug: 'boys-cargo-pants',
    name: 'Boys Cargo Pants',
    brand: 'PlayWorks',
    category: 'clothing',
    subcategory: 'Jeans',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y', '13-16y'],
    description:
      'Rugged cargo pants with multiple utility pockets and an adjustable waistband, built for outdoor adventures. Reinforced knees add extra durability for active kids. A relaxed fit ensures comfort throughout the day.',
    shortDescription: 'Rugged cargo pants with utility pockets.',
    images: ['https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1602293589930-45aad59ba3ab?auto=format&fit=crop&w=800&q=80'],
    price: 799,
    mrp: 1099,
    sizes: ['6-7Y', '7-8Y', '8-9Y', '10-11Y', '12-13Y'],
    colors: [{ name: 'Olive Green', hex: '#6b7a4f' }, { name: 'Khaki', hex: '#c3b091' }],
    material: '100% Cotton Twill',
    careInstructions: 'Machine wash cold',
    rating: 4.2,
    reviewCount: 28,
    onlineStock: 14,
    storeStock: 5,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['cargo', 'outdoor', 'durable'],
  },

  // ===================== FOOTWEAR (10+) =====================
  {
    id: 'p22',
    sku: 'LN-FW-0001',
    slug: 'kids-running-shoes',
    name: 'Kids Running Shoes',
    brand: 'Happy Feet Kids',
    category: 'footwear',
    subcategory: 'Sports Shoes',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'Lightweight running shoes with breathable mesh uppers and cushioned soles for all-day activity. A secure lace-up closure keeps little feet snug during play and sports. Non-slip rubber outsole provides reliable grip on multiple surfaces.',
    shortDescription: 'Lightweight breathable running shoes for active kids.',
    images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
    price: 1299,
    mrp: 1799,
    sizes: ['8', '9', '10', '11', '12', '13'],
    colors: [{ name: 'Black/Red', hex: '#1a1a1a' }, { name: 'Grey/Blue', hex: '#7d8ca3' }],
    material: 'Mesh and EVA Sole',
    careInstructions: 'Wipe clean with damp cloth',
    rating: 4.5,
    reviewCount: 96,
    onlineStock: 26,
    storeStock: 14,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    trending: true,
    tags: ['sports', 'running', 'shoes'],
  },
  {
    id: 'p23',
    sku: 'LN-FW-0002',
    slug: 'girls-casual-sneakers',
    name: 'Girls Casual Sneakers',
    brand: 'Happy Feet Kids',
    category: 'footwear',
    subcategory: 'Sneakers',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'Cute canvas sneakers with a hook-and-loop strap for easy on-off wear, ideal for toddlers learning independence. Cushioned footbed supports growing feet through the day. Fun prints add a playful touch to any outfit.',
    shortDescription: 'Cute canvas sneakers with easy strap closure.',
    images: ['https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
    price: 799,
    mrp: 999,
    sizes: ['5', '6', '7', '8', '9'],
    colors: [{ name: 'Pink', hex: '#e8927c' }, { name: 'White', hex: '#ffffff' }],
    material: 'Canvas and Rubber Sole',
    careInstructions: 'Spot clean with mild soap',
    rating: 4.3,
    reviewCount: 61,
    onlineStock: 22,
    storeStock: 10,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['sneakers', 'casual', 'canvas'],
  },
  {
    id: 'p24',
    sku: 'LN-FW-0003',
    slug: 'kids-school-shoes',
    name: 'Kids School Shoes',
    brand: 'Happy Feet Kids',
    category: 'footwear',
    subcategory: 'School Shoes',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'Durable black school shoes with a slip-resistant sole, designed to meet school uniform requirements. The reinforced toe cap protects against daily wear and tear. A cushioned insole keeps feet comfortable through long school days.',
    shortDescription: 'Durable black school shoes with cushioned insole.',
    images: ['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80'],
    price: 899,
    mrp: 1199,
    sizes: ['9', '10', '11', '12', '13', '1', '2'],
    colors: [{ name: 'Black', hex: '#1a1a1a' }],
    material: 'Synthetic Leather',
    careInstructions: 'Wipe clean, polish as needed',
    rating: 4.4,
    reviewCount: 143,
    onlineStock: 31,
    storeStock: 20,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['school', 'formal', 'uniform'],
  },
  {
    id: 'p25',
    sku: 'LN-FW-0004',
    slug: 'New Born-soft-shoes',
    name: 'New Born Soft Shoes',
    brand: 'Wobble Walk',
    category: 'footwear',
    subcategory: 'New Born Shoes',
    gender: 'New Born',
    ageGroup: ['0-3m', '3-12m'],
    description:
      'Pre-walker shoes made from ultra-soft fabric that mimics barefoot movement for babies just starting to explore. Elastic ankle opening ensures they stay on little feet. Breathable material keeps New Born feet comfortable and cool.',
    shortDescription: 'Ultra-soft pre-walker shoes for babies.',
    images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80'],
    price: 499,
    mrp: 699,
    sizes: ['2', '3', '4'],
    colors: [{ name: 'Beige', hex: '#e8dcc8' }, { name: 'Grey', hex: '#a9a9a9' }],
    material: 'Cotton and Suede',
    careInstructions: 'Hand wash cold',
    rating: 4.6,
    reviewCount: 52,
    onlineStock: 18,
    storeStock: 9,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['New Born', 'pre-walker', 'soft-sole'],
  },
  {
    id: 'p26',
    sku: 'LN-FW-0005',
    slug: 'kids-flip-flop-sandals',
    name: 'Kids Flip Flop Sandals',
    brand: 'Happy Feet Kids',
    category: 'footwear',
    subcategory: 'Sandals',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'Lightweight rubber flip flops perfect for pool days and casual summer outings. Textured footbed prevents slipping when wet. Easy to clean and quick-drying for beach and monsoon use.',
    shortDescription: 'Lightweight rubber flip flops for summer fun.',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&q=80'],
    price: 299,
    mrp: 399,
    sizes: ['6', '7', '8', '9', '10'],
    colors: [{ name: 'Blue', hex: '#3b5998' }, { name: 'Green', hex: '#3f704d' }],
    material: 'Rubber (EVA)',
    careInstructions: 'Rinse with water to clean',
    rating: 4.0,
    reviewCount: 34,
    onlineStock: 40,
    storeStock: 25,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['sandals', 'summer', 'pool'],
  },
  {
    id: 'p27',
    sku: 'LN-FW-0006',
    slug: 'girls-party-belly-shoes',
    name: 'Girls Party Belly Shoes',
    brand: 'Wobble Walk',
    category: 'footwear',
    subcategory: 'Party Shoes',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'Sparkly belly shoes with a soft glitter finish and comfortable elastic strap, perfect for parties and celebrations. Cushioned sole offers comfort for dancing and long events. A must-have for the festive wardrobe.',
    shortDescription: 'Sparkly glitter belly shoes for parties.',
    images: ['https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
    price: 649,
    mrp: 999,
    sizes: ['5', '6', '7', '8', '9'],
    colors: [{ name: 'Gold', hex: '#d4af37' }, { name: 'Silver', hex: '#c0c0c0' }],
    material: 'Synthetic Glitter Fabric',
    careInstructions: 'Wipe clean with dry cloth',
    rating: 4.2,
    reviewCount: 19,
    onlineStock: 10,
    storeStock: 3,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['party', 'glitter', 'festive'],
  },
  {
    id: 'p28',
    sku: 'LN-FW-0007',
    slug: 'boys-velcro-sports-shoes',
    name: 'Boys Velcro Sports Shoes',
    brand: 'Happy Feet Kids',
    category: 'footwear',
    subcategory: 'Sports Shoes',
    gender: 'boys',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'Sporty shoes with double velcro straps for a quick and secure fit, great for kids still mastering laces. Shock-absorbing sole cushions every step during play. Durable outsole withstands outdoor terrain.',
    shortDescription: 'Sporty velcro shoes for easy, secure fit.',
    images: ['https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80'],
    price: 999,
    mrp: 1399,
    sizes: ['6', '7', '8', '9', '10', '11'],
    colors: [{ name: 'Black/Green', hex: '#1a1a1a' }],
    material: 'Mesh and Synthetic',
    careInstructions: 'Wipe clean with damp cloth',
    rating: 4.3,
    reviewCount: 44,
    onlineStock: 0,
    storeStock: 12,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['sports', 'velcro', 'shoes'],
  },
  {
    id: 'p29',
    sku: 'LN-FW-0008',
    slug: 'kids-winter-boots',
    name: 'Kids Winter Boots',
    brand: 'Wobble Walk',
    category: 'footwear',
    subcategory: 'Boots',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'Warm ankle-high boots lined with soft fleece to keep feet cozy in cold weather. Zip closure makes wearing quick and effortless. Non-slip sole is designed for wet and icy surfaces.',
    shortDescription: 'Fleece-lined warm boots for winter weather.',
    images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80'],
    price: 1499,
    mrp: 2199,
    sizes: ['9', '10', '11', '12', '13', '1'],
    colors: [{ name: 'Brown', hex: '#6b4226' }, { name: 'Black', hex: '#1a1a1a' }],
    material: 'Synthetic Leather with Fleece Lining',
    careInstructions: 'Wipe clean, avoid soaking',
    rating: 4.5,
    reviewCount: 23,
    onlineStock: 7,
    storeStock: 5,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['winter', 'boots', 'warm'],
  },
  {
    id: 'p30',
    sku: 'LN-FW-0009',
    slug: 'kids-home-slippers',
    name: 'Kids Home Slippers',
    brand: 'Wobble Walk',
    category: 'footwear',
    subcategory: 'Slippers',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'Soft cushioned slippers designed for indoor comfort with a non-slip base for safety. Fun animal-face design makes them a favorite among toddlers. Lightweight and easy to slip on and off.',
    shortDescription: 'Soft cushioned slippers for indoor comfort.',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&q=80'],
    price: 349,
    mrp: 449,
    sizes: ['5', '6', '7', '8'],
    colors: [{ name: 'Yellow', hex: '#f4d35e' }, { name: 'Pink', hex: '#e8927c' }],
    material: 'EVA Foam',
    careInstructions: 'Wipe clean with damp cloth',
    rating: 4.1,
    reviewCount: 29,
    onlineStock: 24,
    storeStock: 11,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['slippers', 'indoor', 'comfort'],
  },
  {
    id: 'p31',
    sku: 'LN-FW-0010',
    slug: 'girls-mary-jane-school-shoes',
    name: 'Girls Mary Jane School Shoes',
    brand: 'Happy Feet Kids',
    category: 'footwear',
    subcategory: 'School Shoes',
    gender: 'girls',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'Classic Mary Jane style school shoes with a secure buckle strap and polished finish. Cushioned insole provides comfort through long school hours. Sturdy construction ensures they last the full school year.',
    shortDescription: 'Classic buckle-strap Mary Jane school shoes.',
    images: ['https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1514989940723-e8e51635b782?auto=format&fit=crop&w=800&q=80'],
    price: 799,
    mrp: 1099,
    sizes: ['8', '9', '10', '11', '12'],
    colors: [{ name: 'Black', hex: '#1a1a1a' }],
    material: 'Synthetic Leather',
    careInstructions: 'Wipe clean, polish as needed',
    rating: 4.4,
    reviewCount: 37,
    onlineStock: 20,
    storeStock: 10,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['school', 'mary-jane', 'formal'],
  },
  {
    id: 'p32',
    sku: 'LN-FW-0011',
    slug: 'boys-sandals-with-backstrap',
    name: 'Boys Sandals with Backstrap',
    brand: 'Wobble Walk',
    category: 'footwear',
    subcategory: 'Sandals',
    gender: 'boys',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'Sturdy sandals with an adjustable backstrap for a secure fit during outdoor play. Contoured footbed supports natural foot movement. Durable sole is built to handle rough terrain and daily wear.',
    shortDescription: 'Sturdy backstrap sandals for outdoor play.',
    images: ['https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=800&q=80'],
    price: 549,
    mrp: 549,
    sizes: ['6', '7', '8', '9', '10'],
    colors: [{ name: 'Navy Blue', hex: '#1f2a44' }],
    material: 'EVA and Rubber',
    careInstructions: 'Rinse with water to clean',
    rating: 3.9,
    reviewCount: 12,
    onlineStock: 16,
    storeStock: 6,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['sandals', 'outdoor', 'durable'],
  },

  // ===================== TOYS (15+) =====================
  {
    id: 'p33',
    sku: 'LN-TY-0001',
    slug: 'educational-building-blocks',
    name: 'Educational Building Blocks Set',
    brand: 'Little Learners',
    category: 'toys',
    subcategory: 'Building Blocks',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A 120-piece interlocking building block set that encourages creativity, motor skills, and problem-solving. Made from non-toxic, BPA-free plastic that is safe for little hands. Comes in a reusable storage box for easy cleanup.',
    shortDescription: '120-piece safe interlocking blocks for creative play.',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80'],
    price: 899,
    mrp: 1299,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#e8927c' }],
    rating: 4.7,
    reviewCount: 187,
    onlineStock: 33,
    storeStock: 15,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    trending: true,
    tags: ['building-blocks', 'educational', 'stem'],
  },
  {
    id: 'p34',
    sku: 'LN-TY-0002',
    slug: 'remote-control-car',
    name: 'Remote Control Car',
    brand: 'PlayWorks',
    category: 'toys',
    subcategory: 'Remote Control',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A high-speed remote control car with rechargeable battery and off-road tires for indoor and outdoor play. Responsive controls allow full 360-degree maneuverability. Durable shell withstands bumps and falls.',
    shortDescription: 'High-speed rechargeable RC car for indoor/outdoor play.',
    images: ['https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&w=800&q=80'],
    price: 1799,
    mrp: 2499,
    sizes: [],
    colors: [{ name: 'Red', hex: '#c1272d' }, { name: 'Blue', hex: '#3b5998' }],
    rating: 4.4,
    reviewCount: 76,
    onlineStock: 15,
    storeStock: 8,
    pickupAvailable: true,
    featured: true,
    newArrival: true,
    bestSeller: false,
    trending: true,
    tags: ['remote-control', 'car', 'boys-toys'],
  },
  {
    id: 'p35',
    sku: 'LN-TY-0003',
    slug: 'soft-teddy-bear',
    name: 'Soft Teddy Bear',
    brand: 'Bright Buddy',
    category: 'toys',
    subcategory: 'Soft Toys',
    gender: 'unisex',
    ageGroup: ['0-3m', '3-12m', '1-3y'],
    description:
      'A huggable plush teddy bear made from hypoallergenic, super-soft fabric, perfect as a cuddle companion or nursery decor. Securely stitched seams ensure safety for infants and toddlers. Machine washable for easy care.',
    shortDescription: 'Huggable hypoallergenic plush teddy bear.',
    images: ['https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80'],
    price: 599,
    mrp: 799,
    sizes: ['Free Size'],
    colors: [{ name: 'Brown', hex: '#6b4226' }, { name: 'Cream', hex: '#f4ecd8' }],
    rating: 4.8,
    reviewCount: 214,
    onlineStock: 28,
    storeStock: 19,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['soft-toy', 'teddy-bear', 'cuddly'],
  },
  {
    id: 'p36',
    sku: 'LN-TY-0004',
    slug: 'kids-puzzle-set',
    name: 'Kids Wooden Puzzle Set',
    brand: 'Little Learners',
    category: 'toys',
    subcategory: 'Puzzles',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A set of 5 wooden jigsaw puzzles featuring animals, numbers, and alphabets to build cognitive and fine motor skills. Chunky, easy-grip pieces are ideal for small hands. Non-toxic paint finish is safe and vibrant.',
    shortDescription: 'Set of 5 wooden puzzles for early learning.',
    images: ['https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80'],
    price: 649,
    mrp: 899,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#f4d35e' }],
    rating: 4.6,
    reviewCount: 68,
    onlineStock: 20,
    storeStock: 10,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['puzzle', 'wooden', 'educational'],
  },
  {
    id: 'p37',
    sku: 'LN-TY-0005',
    slug: 'doll-house-playset',
    name: 'Doll House Playset',
    brand: 'Bright Buddy',
    category: 'toys',
    subcategory: 'Dolls',
    gender: 'girls',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A three-story dollhouse complete with miniature furniture, accessories, and a working elevator. Encourages imaginative and role-play among children. Sturdy plastic construction ensures durability through years of play.',
    shortDescription: 'Three-story dollhouse with furniture and accessories.',
    images: ['https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=800&q=80'],
    price: 2999,
    mrp: 3999,
    sizes: [],
    colors: [{ name: 'Pink/Purple', hex: '#e8927c' }],
    rating: 4.7,
    reviewCount: 54,
    onlineStock: 6,
    storeStock: 4,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: false,
    trending: true,
    tags: ['dollhouse', 'pretend-play', 'girls-toys'],
  },
  {
    id: 'p38',
    sku: 'LN-TY-0006',
    slug: 'outdoor-cricket-set',
    name: 'Outdoor Cricket Set',
    brand: 'PlayWorks',
    category: 'toys',
    subcategory: 'Outdoor Toys',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A complete junior cricket set including a lightweight bat, soft ball, and stumps designed for young players. Ideal for backyard games and building early sports skills. Comes with a convenient carry bag for storage.',
    shortDescription: 'Junior cricket set with bat, ball, and stumps.',
    images: ['https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?auto=format&fit=crop&w=800&q=80'],
    price: 799,
    mrp: 1099,
    sizes: [],
    colors: [{ name: 'Natural Wood', hex: '#c3b091' }],
    rating: 4.3,
    reviewCount: 41,
    onlineStock: 17,
    storeStock: 8,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['outdoor', 'cricket', 'sports'],
  },
  {
    id: 'p39',
    sku: 'LN-TY-0007',
    slug: 'New Born-activity-gym',
    name: 'New Born Activity Gym',
    brand: 'Nest & Nook',
    category: 'toys',
    subcategory: 'New Born Toys',
    gender: 'New Born',
    ageGroup: ['0-3m', '3-12m'],
    description:
      'A colorful play gym with hanging toys, mirrors, and crinkly textures to stimulate a New Born senses. Soft padded mat provides a comfortable space for tummy time. Foldable frame makes storage and travel convenient.',
    shortDescription: 'Colorful play gym for sensory development.',
    images: ['https://images.unsplash.com/photo-1591382696684-38c427c7547a?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1566454419290-57a64afe30d7?auto=format&fit=crop&w=800&q=80'],
    price: 1499,
    mrp: 1999,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#a8e6cf' }],
    rating: 4.6,
    reviewCount: 63,
    onlineStock: 12,
    storeStock: 6,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['New Born', 'activity-gym', 'sensory'],
  },
  {
    id: 'p40',
    sku: 'LN-TY-0008',
    slug: 'musical-keyboard-toy',
    name: 'Musical Keyboard Toy',
    brand: 'Bright Buddy',
    category: 'toys',
    subcategory: 'Musical Toys',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A kid-friendly electronic keyboard with multiple sound effects, demo songs, and a built-in microphone. Introduces children to music and rhythm in a fun, interactive way. Bright buttons and lights capture young attention spans.',
    shortDescription: 'Interactive electronic keyboard with mic and sounds.',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80'],
    price: 1299,
    mrp: 1799,
    sizes: [],
    colors: [{ name: 'Red/Yellow', hex: '#c1272d' }],
    rating: 4.2,
    reviewCount: 35,
    onlineStock: 14,
    storeStock: 5,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['musical', 'keyboard', 'interactive'],
  },
  {
    id: 'p41',
    sku: 'LN-TY-0009',
    slug: 'stem-robotics-kit',
    name: 'STEM Robotics Kit',
    brand: 'Little Learners',
    category: 'toys',
    subcategory: 'STEM Toys',
    gender: 'unisex',
    ageGroup: ['8-12y', '13-16y'],
    description:
      'An educational robotics kit that teaches basic coding and engineering concepts through hands-on assembly. Includes motors, sensors, and a simple app-based programming interface. Great for building STEM skills through play.',
    shortDescription: 'Hands-on robotics kit teaching coding basics.',
    images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1618842676088-c4d48a6a7c9d?auto=format&fit=crop&w=800&q=80'],
    price: 3499,
    mrp: 4499,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#3fb8af' }],
    rating: 4.8,
    reviewCount: 47,
    onlineStock: 9,
    storeStock: 3,
    pickupAvailable: true,
    featured: true,
    newArrival: true,
    bestSeller: false,
    trending: true,
    tags: ['stem', 'robotics', 'coding'],
  },
  {
    id: 'p42',
    sku: 'LN-TY-0010',
    slug: 'family-board-game',
    name: 'Family Board Game Pack',
    brand: 'Little Learners',
    category: 'toys',
    subcategory: 'Board Games',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A pack of three classic board games designed for family game nights, promoting strategy and social skills. Easy-to-understand rules make it accessible for younger kids. Compact packaging is perfect for travel and storage.',
    shortDescription: 'Pack of 3 classic games for family fun.',
    images: ['https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=800&q=80'],
    price: 599,
    mrp: 799,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#f4d35e' }],
    rating: 4.5,
    reviewCount: 88,
    onlineStock: 25,
    storeStock: 12,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['board-game', 'family', 'strategy'],
  },
  {
    id: 'p43',
    sku: 'LN-TY-0011',
    slug: 'push-and-pull-walker-toy',
    name: 'Push and Pull Walker Toy',
    brand: 'Nest & Nook',
    category: 'toys',
    subcategory: 'New Born Toys',
    gender: 'New Born',
    ageGroup: ['3-12m', '1-3y'],
    description:
      'A sturdy walker toy with fun rattling beads and shape sorters, designed to support babies as they learn to walk. Wide base offers stability while adding confidence to early steps. Bright colors and sounds keep babies engaged.',
    shortDescription: 'Sturdy walker toy supporting babies first steps.',
    images: ['https://images.unsplash.com/photo-1591382696684-38c427c7547a?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1566454419290-57a64afe30d7?auto=format&fit=crop&w=800&q=80'],
    price: 1199,
    mrp: 1599,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#8ec9e8' }],
    rating: 4.5,
    reviewCount: 57,
    onlineStock: 16,
    storeStock: 7,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['New Born', 'walker', 'first-steps'],
  },
  {
    id: 'p44',
    sku: 'LN-TY-0012',
    slug: 'plush-bunny-soft-toy',
    name: 'Plush Bunny Soft Toy',
    brand: 'Bright Buddy',
    category: 'toys',
    subcategory: 'Soft Toys',
    gender: 'unisex',
    ageGroup: ['0-3m', '3-12m', '1-3y'],
    description:
      'A soft, floppy-eared bunny plush made from premium minky fabric that is gentle against New Born skin. Weighted bottom helps it sit upright for playtime. A perfect first soft toy or gifting option for newborns.',
    shortDescription: 'Soft floppy-eared bunny plush for babies.',
    images: ['https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80'],
    price: 499,
    mrp: 699,
    sizes: ['Free Size'],
    colors: [{ name: 'White', hex: '#ffffff' }, { name: 'Grey', hex: '#a9a9a9' }],
    rating: 4.7,
    reviewCount: 102,
    onlineStock: 30,
    storeStock: 14,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['soft-toy', 'bunny', 'newborn-gift'],
  },
  {
    id: 'p45',
    sku: 'LN-TY-0013',
    slug: 'kids-art-and-craft-kit',
    name: 'Kids Art and Craft Kit',
    brand: 'Little Learners',
    category: 'toys',
    subcategory: 'Educational Toys',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A comprehensive craft kit with crayons, sketch pads, stickers, and modeling clay to spark creativity. Encourages fine motor skills and artistic expression in a mess-friendly kit. Non-toxic materials are safe for young artists.',
    shortDescription: 'Comprehensive craft kit for creative expression.',
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80'],
    price: 699,
    mrp: 999,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#e8927c' }],
    rating: 4.4,
    reviewCount: 39,
    onlineStock: 19,
    storeStock: 8,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: false,
    trending: false,
    tags: ['art', 'craft', 'creative'],
  },
  {
    id: 'p46',
    sku: 'LN-TY-0014',
    slug: 'kids-scooter-3-wheel',
    name: 'Kids 3-Wheel Scooter',
    brand: 'PlayWorks',
    category: 'toys',
    subcategory: 'Outdoor Toys',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A stable three-wheel scooter with an adjustable handlebar height that grows with your child. Lean-to-steer mechanism helps develop balance and coordination. Sturdy deck and smooth-rolling wheels ensure a safe ride.',
    shortDescription: 'Stable 3-wheel scooter with adjustable height.',
    images: ['https://images.unsplash.com/photo-1472162072942-cd5147eb3902?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1519340241574-2cec6aef0c01?auto=format&fit=crop&w=800&q=80'],
    price: 2199,
    mrp: 2999,
    sizes: [],
    colors: [{ name: 'Blue', hex: '#3b5998' }, { name: 'Pink', hex: '#e8927c' }],
    rating: 4.6,
    reviewCount: 71,
    onlineStock: 11,
    storeStock: 5,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: false,
    trending: true,
    tags: ['scooter', 'outdoor', 'balance'],
  },
  {
    id: 'p47',
    sku: 'LN-TY-0015',
    slug: 'toy-kitchen-playset',
    name: 'Toy Kitchen Playset',
    brand: 'Bright Buddy',
    category: 'toys',
    subcategory: 'Educational Toys',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A miniature kitchen playset with a stove, sink, and pretend food accessories for imaginative role play. Realistic sounds and lights make cooking play more immersive. Encourages social skills through shared play.',
    shortDescription: 'Miniature kitchen playset for imaginative play.',
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80'],
    price: 2499,
    mrp: 3299,
    sizes: [],
    colors: [{ name: 'Pink/White', hex: '#f2c6c2' }],
    rating: 4.5,
    reviewCount: 48,
    onlineStock: 8,
    storeStock: 4,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['kitchen', 'pretend-play', 'role-play'],
  },
  {
    id: 'p48',
    sku: 'LN-TY-0016',
    slug: 'magnetic-alphabet-tiles',
    name: 'Magnetic Alphabet Tiles',
    brand: 'Little Learners',
    category: 'toys',
    subcategory: 'Educational Toys',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A set of 52 magnetic alphabet tiles that help children learn letter recognition and early spelling. Works on any magnetic surface including the fridge or a whiteboard. Durable plastic construction resists chipping and fading.',
    shortDescription: 'Set of 52 magnetic tiles for letter learning.',
    images: ['https://images.unsplash.com/photo-1503676260728-1c00da094a0b?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80'],
    price: 399,
    mrp: 549,
    sizes: [],
    colors: [{ name: 'Multicolor', hex: '#f4d35e' }],
    rating: 4.3,
    reviewCount: 29,
    onlineStock: 22,
    storeStock: 9,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['magnetic', 'alphabet', 'educational'],
  },

  // ===================== ACCESSORIES (5+) =====================
  {
    id: 'p49',
    sku: 'LN-AC-0001',
    slug: 'kids-school-backpack',
    name: 'Kids School Backpack',
    brand: 'Cub Club',
    category: 'accessories',
    subcategory: 'Bags',
    gender: 'unisex',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'A spacious school backpack with padded shoulder straps and multiple compartments for books and lunch boxes. Water-resistant fabric protects contents from light rain. Reflective piping adds visibility for safety.',
    shortDescription: 'Spacious padded backpack for school essentials.',
    images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=800&q=80'],
    price: 899,
    mrp: 1299,
    sizes: ['Free Size'],
    colors: [{ name: 'Navy Blue', hex: '#1f2a44' }, { name: 'Red', hex: '#c1272d' }],
    material: 'Polyester',
    careInstructions: 'Wipe clean with damp cloth',
    rating: 4.5,
    reviewCount: 92,
    onlineStock: 21,
    storeStock: 10,
    pickupAvailable: true,
    featured: true,
    newArrival: false,
    bestSeller: true,
    trending: false,
    tags: ['backpack', 'school', 'bag'],
  },
  {
    id: 'p50',
    sku: 'LN-AC-0002',
    slug: 'boys-printed-cap',
    name: 'Boys Printed Cap',
    brand: 'Giggle Gear',
    category: 'accessories',
    subcategory: 'Caps',
    gender: 'boys',
    ageGroup: ['1-3y', '4-7y', '8-12y'],
    description:
      'A cotton baseball cap with an adjustable strap for a comfortable, growing fit. Provides sun protection during outdoor play and travel. Fun prints make it a favorite everyday accessory.',
    shortDescription: 'Adjustable cotton cap for sun protection.',
    images: ['https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1519238359922-989348752efb?auto=format&fit=crop&w=800&q=80'],
    price: 249,
    mrp: 349,
    sizes: ['Free Size'],
    colors: [{ name: 'Navy Blue', hex: '#1f2a44' }, { name: 'Grey', hex: '#a9a9a9' }],
    material: '100% Cotton',
    careInstructions: 'Hand wash cold',
    rating: 4.1,
    reviewCount: 24,
    onlineStock: 27,
    storeStock: 12,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['cap', 'sun-protection', 'casual'],
  },
  {
    id: 'p51',
    sku: 'LN-AC-0003',
    slug: 'girls-hair-accessory-set',
    name: 'Girls Hair Accessory Set',
    brand: 'Sunny Sprouts',
    category: 'accessories',
    subcategory: 'Hair Accessories',
    gender: 'girls',
    ageGroup: ['1-3y', '4-7y'],
    description:
      'A 20-piece hair accessory set including bows, clips, and scrunchies in vibrant colors and patterns. Gentle grip design prevents hair damage and discomfort. Comes in a reusable organizer pouch for easy storage.',
    shortDescription: '20-piece colorful hair accessory set.',
    images: ['https://images.unsplash.com/photo-1522771930-78848d9293e8?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?auto=format&fit=crop&w=800&q=80'],
    price: 199,
    mrp: 299,
    sizes: ['Free Size'],
    colors: [{ name: 'Multicolor', hex: '#e8927c' }],
    material: 'Fabric and Metal Alloy',
    careInstructions: 'Wipe clean',
    rating: 4.4,
    reviewCount: 66,
    onlineStock: 35,
    storeStock: 15,
    pickupAvailable: true,
    featured: false,
    newArrival: true,
    bestSeller: true,
    trending: false,
    tags: ['hair-accessories', 'bows', 'clips'],
  },
  {
    id: 'p52',
    sku: 'LN-AC-0004',
    slug: 'kids-cotton-socks-pack',
    name: 'Kids Cotton Socks Pack of 5',
    brand: 'Nest & Nook',
    category: 'accessories',
    subcategory: 'Socks',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y', '8-12y'],
    description:
      'A pack of five breathable cotton socks with reinforced heels and toes for extra durability. Soft elastic cuffs prevent slipping without leaving marks. A daily essential for school and casual wear.',
    shortDescription: 'Pack of 5 breathable cotton socks.',
    images: ['https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
    price: 299,
    mrp: 399,
    sizes: ['Free Size'],
    colors: [{ name: 'Assorted', hex: '#a9a9a9' }],
    material: '80% Cotton 15% Polyester 5% Elastane',
    careInstructions: 'Machine wash warm',
    rating: 4.2,
    reviewCount: 45,
    onlineStock: 38,
    storeStock: 20,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['socks', 'cotton', 'essentials'],
  },
  {
    id: 'p53',
    sku: 'LN-AC-0005',
    slug: 'kids-sunglasses',
    name: 'Kids UV Protection Sunglasses',
    brand: 'Tiny Trails',
    category: 'accessories',
    subcategory: 'Sunglasses',
    gender: 'unisex',
    ageGroup: ['1-3y', '4-7y', '8-12y'],
    description:
      'Lightweight sunglasses with UV400 protection lenses to shield young eyes from harmful sun rays. Flexible frame resists bending and breaking during active play. Comes with a protective pouch for storage.',
    shortDescription: 'UV400 protection sunglasses with flexible frame.',
    images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1520367445093-50dc08a59d9d?auto=format&fit=crop&w=800&q=80'],
    price: 399,
    mrp: 599,
    sizes: ['Free Size'],
    colors: [{ name: 'Black', hex: '#1a1a1a' }, { name: 'Blue', hex: '#3b5998' }],
    material: 'Polycarbonate',
    careInstructions: 'Wipe with microfiber cloth',
    rating: 4.0,
    reviewCount: 17,
    onlineStock: 0,
    storeStock: 0,
    pickupAvailable: false,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['sunglasses', 'uv-protection', 'summer'],
  },
  {
    id: 'p54',
    sku: 'LN-AC-0006',
    slug: 'kids-adjustable-belt',
    name: 'Kids Adjustable Belt',
    brand: 'Cub Club',
    category: 'accessories',
    subcategory: 'Belts',
    gender: 'boys',
    ageGroup: ['4-7y', '8-12y'],
    description:
      'An adjustable faux-leather belt with a sturdy buckle, designed to fit growing waistlines comfortably. Complements school uniforms and casual outfits alike. Punch-free design allows infinite size adjustment.',
    shortDescription: 'Adjustable faux-leather belt for school and casual wear.',
    images: ['https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=80', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80'],
    price: 349,
    mrp: 499,
    sizes: ['Free Size'],
    colors: [{ name: 'Black', hex: '#1a1a1a' }, { name: 'Brown', hex: '#6b4226' }],
    material: 'Faux Leather',
    careInstructions: 'Wipe clean with dry cloth',
    rating: 4.1,
    reviewCount: 14,
    onlineStock: 23,
    storeStock: 9,
    pickupAvailable: true,
    featured: false,
    newArrival: false,
    bestSeller: false,
    trending: false,
    tags: ['belt', 'school', 'accessories'],
  },
]

export default products
